name: srl
description: A test project for states_rebuilder, live streamed by Luke Pighetti & GroovinChip.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  geolocator: 
  http:
  intl:
  json_annotation:
  lottie:
  salomon_bottom_bar:
  shared_preferences:
  states_rebuilder:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

  fonts:
    - family: Brandon
      fonts:
        - asset: assets/fonts/Brandon-Regular.otf
        - asset: assets/fonts/Brandon-Bold.otf
          weight: 700

    - family: SRLIcons
      fonts:
        - asset: assets/icons/SRLIcons.ttf
